###buscar
GET http://localhost:3100/api/empleados HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwYWZlNTEzOTE3MGIxMjE4NDU4ODYwNyIsIm5hbWUiOiJSaWNhcmRvMiIsImVtYWlsIjoicmljYXJkb2hoQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJEE5QUNyU1BnMnUwSXdWVXhkbktBRi5SN1hTd1NMVGl0RldqNy5nb29hMDRQclB6SGVQY3BLIiwiX192IjowfSwiaWF0IjoxNjIyNDkxNTQ5LCJleHAiOjE2MjI0OTUxNDl9.ko2DeRV_6dRgQmajC5WdquFRpPGTBFFla_tVRGGU_7w

###Insertar prdocuto 
POST http://localhost:3100/api/empleados HTTP/1.1
Content-Type: application/json

{
    "nombre": "Richiety",
    "puesto": "Goku jr",
    "departamento":"computer science",
    "salario": 200
}


###Consutlar por ID
GET http://localhost:3100/api/empleados/6081c4280ed06218e43bd2a6 HTTP/1.1

###Actualizar por ID
PUT http://localhost:3100/api/empleados/6081c4280ed06218e43bd2a6 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ricardo",
    "puesto": "Developer jr",
    "departamento":"computer science",
    "salario": 22000
}

###Eliminar por ID
DELETE  http://localhost:3100/api/empleados/6081c4280ed06218e43bd2a6 HTTP/1.1
Content-Type: application/json

###Iniciar sesion
POST http://localhost:3100/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "ricardo@gmail.com",
    "password": "Ricardo123"
}

###Usuarios
GET http://localhost:3100/api/users HTTP/1.1
Content-Type: application/json
Authorization: token-auth eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwYWJmYzY2MDE1YTljMWU3NGJlODlkNSIsIm5hbWUiOiJSaWNhcmRvIiwiZW1haWwiOiJyaWNhcmRvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJGk4WXk5eDNhOXVOYzZCT0N6b3lZQXVOWUZBNW0zemkwejVDUzB3a0dEME0zbmZsRnhHNS8uIiwiX192IjowfSwiaWF0IjoxNjIzMTc2ODE0LCJleHAiOjE2MjMxODA0MTR9.mzn78QaAjMVHnYH0Hms4QPDrKy5Wtr1flkFm6PNvVOg

###Crear un usuario
POST http://localhost:3100/api/users HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwYWJmYzY2MDE1YTljMWU3NGJlODlkNSIsIm5hbWUiOiJSaWNhcmRvIiwiZW1haWwiOiJyaWNhcmRvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJGk4WXk5eDNhOXVOYzZCT0N6b3lZQXVOWUZBNW0zemkwejVDUzB3a0dEME0zbmZsRnhHNS8uIiwiX192IjowfSwiaWF0IjoxNjIyNTc4OTUyLCJleHAiOjE2MjI1ODI1NTJ9.lN2WwPSKrqYKyb3WL2TRwmdJ_MyJyW-V97Lt1K7X1Nk

{
    "name": "RicardoAd",
    "email": "ricardoad@gmail.com",
    "password": "Ricardo123ad",
    "tipo": 1

}

###Consultar por ID
GET http://localhost:3100/api/users/60abfc66015a9c1e74be89d5 HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwYWJmYzY2MDE1YTljMWU3NGJlODlkNSIsIm5hbWUiOiJSaWNhcmRvIiwiZW1haWwiOiJyaWNhcmRvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJGk4WXk5eDNhOXVOYzZCT0N6b3lZQXVOWUZBNW0zemkwejVDUzB3a0dEME0zbmZsRnhHNS8uIiwiX192IjowfSwiaWF0IjoxNjIyNTc4OTUyLCJleHAiOjE2MjI1ODI1NTJ9.lN2WwPSKrqYKyb3WL2TRwmdJ_MyJyW-V97Lt1K7X1Nk

###ELiminar un usuario por ID
DELETE http://localhost:3100/api/users/60b54ccb4994aa182c5e428f HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwYWJmYzY2MDE1YTljMWU3NGJlODlkNSIsIm5hbWUiOiJSaWNhcmRvIiwiZW1haWwiOiJyaWNhcmRvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJGk4WXk5eDNhOXVOYzZCT0N6b3lZQXVOWUZBNW0zemkwejVDUzB3a0dEME0zbmZsRnhHNS8uIiwiX192IjowfSwiaWF0IjoxNjIyNTc4OTUyLCJleHAiOjE2MjI1ODI1NTJ9.lN2WwPSKrqYKyb3WL2TRwmdJ_MyJyW-V97Lt1K7X1Nk

###Modificar un usuario por ID
PUT http://localhost:3100/api/users/60b6975e0ae76904c46d4eec HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwYWJmYzY2MDE1YTljMWU3NGJlODlkNSIsIm5hbWUiOiJSaWNhcmRvIiwiZW1haWwiOiJyaWNhcmRvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJGk4WXk5eDNhOXVOYzZCT0N6b3lZQXVOWUZBNW0zemkwejVDUzB3a0dEME0zbmZsRnhHNS8uIiwiX192IjowfSwiaWF0IjoxNjIyNTc4OTUyLCJleHAiOjE2MjI1ODI1NTJ9.lN2WwPSKrqYKyb3WL2TRwmdJ_MyJyW-V97Lt1K7X1Nk

{
    "name": "Ricardo354",
    "email": "ricardohh354@gmail.com",
    "password": "Ricardo123"
}